package rd.dalventa.api.audit.domain;

public enum AuditAction {
    SALE_VOID,
    INVENTORY_ADJUSTMENT,
    USER_PERMISSION_OVERRIDE,
    USER_PASSWORD_SET,
    PRODUCT_STATUS_CHANGE,
    PRODUCT_PRICE_CHANGE,
    CASH_SHIFT_CLOSE,
    INVOICE_SETTINGS_UPDATE,
    DAILY_CLOSE_CREATE
}
