INSERT INTO role_permissions (role, code, created_at, updated_at) VALUES
    ('ADMIN', 'INVENTORY_VIEW', NOW(), NOW()),
    ('ADMIN', 'INVENTORY_CREATE', NOW(), NOW()),
    ('ADMIN', 'INVENTORY_EDIT', NOW(), NOW()),
    ('ADMIN', 'INVENTORY_ADJUST', NOW(), NOW()),
    ('ADMIN', 'COST_VIEW', NOW(), NOW()),
    ('ADMIN', 'PRICE_VIEW', NOW(), NOW()),
    ('ADMIN', 'SALE_CREATE', NOW(), NOW()),
    ('ADMIN', 'SALE_DISCOUNT', NOW(), NOW()),
    ('ADMIN', 'SALE_PRICE_OVERRIDE', NOW(), NOW()),
    ('ADMIN', 'SALE_VOID', NOW(), NOW()),
    ('ADMIN', 'SALE_RETURN', NOW(), NOW()),
    ('ADMIN', 'CASHSHIFT_OPEN', NOW(), NOW()),
    ('ADMIN', 'CASHSHIFT_CLOSE', NOW(), NOW()),
    ('ADMIN', 'CASHSHIFT_VIEW_HISTORY', NOW(), NOW()),
    ('ADMIN', 'CUSTOMER_CREATE', NOW(), NOW()),
    ('ADMIN', 'CUSTOMER_EDIT', NOW(), NOW()),
    ('ADMIN', 'CREDIT_AUTHORIZE', NOW(), NOW()),
    ('ADMIN', 'CREDIT_RECEIVE_PAYMENT', NOW(), NOW()),
    ('ADMIN', 'REPORTS_VIEW', NOW(), NOW()),
    ('ADMIN', 'PROFIT_VIEW', NOW(), NOW()),
    ('ADMIN', 'USERS_MANAGE', NOW(), NOW()),
    ('ADMIN', 'SETTINGS_MANAGE', NOW(), NOW()),
    ('ADMIN', 'AUDIT_VIEW', NOW(), NOW()),
    ('ADMIN', 'DASHBOARD_VIEW', NOW(), NOW()),
    ('ADMIN', 'SALE_VIEW_HISTORY', NOW(), NOW()),
    ('ADMIN', 'CUSTOMER_VIEW', NOW(), NOW())
ON CONFLICT (role, code) DO NOTHING;
